### ISSUE TITLE
Just a usage question

### ISSUE THREAD

**Issue by sjmcdowall** [HKUST-VISLab/koa-session-ts#15]
I am trying to use this in my TS node project ..  and I am using a Redis store (or planning to) .. but I don't want to use Cookies at all, rather I want to use a JWT that comes in ..  I am thinking I can overwrite the gedSid to use the JWT to generate the SID, which would then be used  for any set/get's ?  Am I reading this right?  Am I on the right track here at all? :)  Cheers!

Looking at the code -- it doesn't seem like the above is sufficient .. This seems pretty tied into using Cookies to get a SessionId and a bunch of stuff that isn't needed if not using Cookies??  :(

**Comment by chenzhutian** [comment]
Wow, I have a little bit forgot the code.
But as my understanding, the Cookies are tightly integrated into the middleware.
I think maybe you will need to re-write a lot of code to get rid of the Cookies

**Comment by sjmcdowall** [comment]
I think you are right :)
